
#Adaptive Performance Tweaks: Spawn
["Mekanism Spawn Config"]
	Enabled = true
	Id = "mekanismadditions"
	#Range: 1 ~ 64
	MaxPassiveMobsPerPlayer = 4
	#Range: 1 ~ 512
	MaxPassiveMobsPerWorld = 12
	#List of passive Mobs to optimize in the format ["minecraft:bat", "minecraft:cat", ..]
	PassiveMobsList = []
	#Range: 1 ~ 64
	MaxNeutralMobsPerPlayer = 4
	#Range: 1 ~ 512
	MaxNeutralMobsPerWorld = 16
	#List of neutral Mobs to optimize in the format ["minecraft:bee", "minecraft:wolf", ..]
	NeutralMobsList = []
	#Range: 1 ~ 64
	MaxHostileMobsPerPlayer = 4
	#Range: 1 ~ 512
	MaxHostileMobsPerWorld = 16
	#List of hostile Mobs to optimize in the format ["minecraft:blaze", "minecraft:cave_spider", ..]
	HostileMobsList = ["mekanismadditions:baby_creeper", "mekanismadditions:baby_enderman", "mekanismadditions:baby_skeleton", "mekanismadditions:baby_stray", "mekanismadditions:baby_wither_skeleton"]

