
#Enchantment Options
[enchantment_options]
	#Top tier enchantments only [default: false]
	ancientManuscriptsTopTierEnchanmentsOnly = false
	#Vanilla enchantments only [default: false]
	ancientManuscriptsVanillaEnchanmentsOnly = false
	#Include curse enchantments [default: false]
	ancientManuscriptsIncludeCurseEnchanments = false
	#Allow treasure enchantments [default: true]
	ancientManuscriptsAllowTreasureEnchanments = true

#Crafting Options
[crafting_options]
	#Glue uses [default: 20]
	#Range: 1 ~ 100
	magicBookGlueDurability = 20
	#Allow enchanted books in recipe [default: true]
	ancientManuscriptsEnchantedBookInRecipeEnabled = true
	#Maximum book enchantments [default: 5]
	#Range: 1 ~ 10
	maximumBookEnchantments = 5
	#Crafting time in seconds [default: 15]
	#Range: 1 ~ 100
	craftingTimeInSeconds = 15

#Trade Options
[trade_options]

	#Villager Trades
	[trade_options.villager_trades]
		#Villager trades enabled [default: true]
		villagerTradesEnabled = true
		#Villager trade level [default: 3]
		#Range: 1 ~ 5
		villagerTradeLevel = 3
		#Villager max trades [default: 2]
		#Range: 1 ~ 20
		villagerMaxTradeCount = 2
		#Villager trade cost [default: 20]
		#Range: 1 ~ 50
		villagerTradeCost = 20

	#Wandering Trader Trades
	[trade_options.wandering_trader_trades]
		#Wandering Trader trades enabled [default: true]
		wanderingTraderTradesEnabled = true
		#Wandering Trader max trades [default: 2]
		#Range: 1 ~ 20
		wanderingTraderMaxTradeCount = 2
		#Wandering Trader trade cost [default: 30]
		#Range: 1 ~ 50
		wanderingTraderTradeCost = 30

