
["[-----AutoMessage Common Configuration-----]"]
	# The messages to be sent
	MESSAGES = ["Default message #1! Sends after 5 seconds, only once ever!", "Default message #2! Sends after 6 seconds, 5 times every session!"]
	# Should we attach a link to this message?
	LINKS = ["https://www.google.com", "https://www.yahoo.com"]
	# How frequently / after how long should the message be sent?
	INTERVALS = [5, 6]
	# How many times should the message be sent per session? 0 = infinite
	SOFT_LIMITS = [1, 5]
	# How many times should the message be sent EVER? 0 = infinite
	HARD_LIMITS = [1, 0]
	# Should AutoMessage be Enabled? default: false
	AM_ENABLED = false

