
# Common configuration settings
[common]
	# If enabled, hides the config button from the backpack screen
	# Valid values: true, false
	keepBackpackOnDeath = false
	# The amount of slot columns in the backpack inventory.
	# Valid range: 1 to 13 (inclusive)
	backpackInventorySizeColumns = 9
	# The amount of slot rows in the backpack inventory.
	# Valid range: 1 to 7 (inclusive)
	backpackInventorySize = 4

	[common.wandering_trader]
		# If enabled, hides the config button from the backpack screen
		# Valid values: true, false
		spawnBackpackOnWanderingTraders = true
		# The chance a Wandering Trader will spawn with a backpack. The chance is interpreted as one out of x, with x being the number given from this config option.
		# Valid range: 1 to 100 (inclusive)
		wanderingTraderBackpackChance = 2
		# The maximum distance a Wandering Trader can detect a player. The longer the distance, the more difficult the challenge to pickpocket their backpack.
		# Valid range: 1 to 32 (inclusive)
		wanderingTraderMaxDetectionDistance = 10.0
		# The time (in ticks) a Wandering Trader will wait before it decides to forget about a detected player. The Wandering Trader will wait indefinitely if the detected player is within the maximum detection distance.
		# Valid range: 1 to 12000 (inclusive)
		wanderingTraderForgetTime = 200
		# If true, allows players who are disliked by Wandering Traders to continue to trade normally with them. A player is considered disliked if they are caught when trying to pickpocket a Wandering Trader's backpack.
		# Valid values: true, false
		dislikedPlayersCanTrade = false
		# The amount of time (in ticks) a player has to wait before a Wandering Trader will like them again. If a player gets caught pickpocketing a Wandering Trader, the cooldown will be reset
		# Valid range: 0 to 24000 (inclusive)
		dislikeCooldown = 6000
		# Instead of generating trades as loot in the Wandering Traders backpacks, only generate emeralds.
		# Valid values: true, false
		generateEmeraldsOnly = false
		# The maximum multiplier to apply when generating loot in the Wandering Trader backpack
		# Valid range: 1 to 64 (inclusive)
		maxLootMultiplier = 12
		# The maximum size of an emerald stack that can generate in the Wandering Trader backpack
		# Valid range: 1 to 64 (inclusive)
		maxEmeraldStack = 32

