
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 887839
	#The name of the modpack
	modpackName = "Fearn Nightfall"
	#The version of the modpack
	modpackVersion = "v6"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

