
[Main]
	#If enabled, you will receive guide books during the game
	"Grant Guide Books" = true

[Teleportation]
	#If enabled, teleporting to mod dimensions can only be done from a certain other dimension
	"Require Dimension" = true
	#Maximum height required for teleportation to Garhenna dimension (Null value allows any)
	"Garhenna Teleportation Height" = 6.0
	#Allows players to teleport to other dimensions from the mod's dimensions
	"Allow Portals" = false

[Researches]
	#Modifier for the time required for one research attempt
	"Research Time Modifier" = 1.0
	#Modifier of experience gained after completing research
	"Research Experience Reward Modifier" = 1.0

[Rituals]
	#Modifier of the energy required for the ritual
	"Required Energy Modifier" = 1.0
	#Modifier for the experience levels required for the ritual
	"Required Experience Modifier" = 1.0
	#Modifier of recovery after ritual
	"Recovery Modifier" = 1.0

[Garhenna]
	#Garhenna Depletion effect will not be applied to you in this dimension
	"Disable Garhenna Depletion" = false
	#Maximum number of Garhenna Depletion points at which player dies. Other negative effects will also be applied depending on this value
	"Max Garhenna Depletion" = 20000.0

