
["Common configs for The End of Herobrine Mod"]
	#Should the Builder build the 1.7.10 structures?
	legacyStructures = true
	#
	### Possession ###
	#
	#Should mobs get possessed?
	mobPossession = false
	#The chance out of a hundred that herobrine will spawn
	#Range: 0 ~ 100
	spawnChance = 1
	#Should spawn herobrine builder?
	spawnBuilder = false
	#Should possessed animals convert back?
	convertBack = true
	#Time in ticks mobs will remain possessed #Default: 1/2 minecraft day
	#Range: > 0
	remainPossessed = 12000
	#
	### Herobrine Spawn Rate ###
	#
	#Minimum time in ticks the mod will wait to try to execute herobrine spawn logic
	#Range: > 0
	tickDelay = 6000
	#Time in ticks herobrine will wait to try to spawn again
	#Range: > 0
	spawnDelay = 6000

