
[Phases]
	#Default 1000
	"Sets points required to enter phase 1" = 1000
	#Default 10000
	"Sets points required to enter phase 2" = 10000
	#Default 50000
	"Sets points required to enter phase 3" = 50000
	#Default 500000
	"Sets points required to enter phase 4" = 500000
	#Default 2000000
	"Sets points required to enter phase 5" = 2000000

["Main Hand Items for the Mutated Player"]
	"Main Hand Slot for the Mutated Player" = ["minecraft:stone_sword|20", "minecraft:stone_axe|20", "minecraft:iron_axe|15", "minecraft:iron_pickaxe|35", "minecraft:stone_pickaxe|25", "minecraft:iron_sword|25"]

["Device Points"]
	#Default 1000
	"Sets points that will be added / subtracted by the devices" = 1000

["player Names"]
	"mutated player Possible Names" = ["ASEStefan", "Nightfox", "Kronoz", "DAKOTA", "JC", "Korben", "Beta", "Renovated", "TeamAbyssal", "XEliteXCraftersX", "TqLxQuanZ", "Ian", "Andy", "Spaghetti", "AnnoyingSrpFan123", "YOASOBI", "Quattro", "NotMilkyCat", "Daralexen", "Chickon98", "ChingChilly", "wRatte", "ivan", "PHO3N1X", "TaiwanIsTheTrueChina", "kevin", "WinVic", "Wikipedia", "Mr.Lambert", "Dr.Pilot", "Harbinger", "LukeUCraft", "purpleskittle", "Adrian", "Isha21", "WitherBean", "Dr.Korpus", "Dr.Simon", "Dr.Robert", "MarioThePlumber", "Lelouch VI Britannia", "Light Yagami", "Mutationcraft", "yorkmousemodz", "Mattias", "entiral", "Cock Jamers", "Chad", "DopeMan", "FlipperIvy"]

