
[IDAS]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	[IDAS.General]
		# Whether or not Ice and Fire structures should be disabled.
		# Default: true
		#
		"Disable Ice and Fire Structures" = true
		# Whether or not mining fatigue is applied to players in the Labyrinth if it has not yet been cleared.
		# Default: true
		#
		"Apply Mining Fatigue" = true

