#If you're looking for Module Configuration, it's in the "serverconfig" directory in the world file!
#
#Combat Debug Mode will show the id of damage sources and entities. Useful for getting the ids of other mods for the combat module's blacklist
combatDebugMode = false

