# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
cosmeticScreenKeybind: true
globalTooltip: false
noMicrosoftTelemetry: true
debug:
  tagsTooltip: false
  debugTooltipMsg: false
  tagsTooltipAppendKeybindHint: true
  tagsPerPage: 6
  NBTTooltip: false
  F3CopyInInventory: true
suppressExperimentalSettingsWarning: false
