
[Mechanics]
	#use 'often' (5000 - 10000 ticks), 'normal' (10000 - 20000 ticks) or 'rare' (20000 - 50000 ticks)
	"spawn rate:" = "normal"
	#if true, the man will summon lightnings if the player is at least three blocks higher than the mans y-coordinate 
	"anti pillar:" = true
	#The highest duration in TICKS in a chase until the man despawns
	"chase duration:" = 600.0
	#The max distance, in a square cube from the man, to the man until it vanishes (30 would mean that you can walk 15 blocks to him until it vanishes)
	"vanish distance:" = 30.0

