#The maximum number of Maps (Filled & Empty combined) allowed to be inside an Atlas (-1 to disable).
maxMapCount = 512
#If enabled, you can increase the Empty Map count by inserting Paper
acceptPaperForEmptyMaps = false
#If true, the Atlas is required to have spare Empty Maps stored to expand the Filled Map size
requireEmptyMapsToExpand = true
#Controls how many usable Maps are added when you add a single Map to the Atlas
#Range: 0 ~ 64
mapEntryValueMultiplier = 1
#Controls how many free Empty Maps you get for 'activating' an Inactive Atlas
#Range: 0 ~ 64
pityActivationMapCount = 9
#If 'true', Atlases will be able to store Empty Maps and auto-fill them as you explore.
enableEmptyMapEntryAndFill = true
#Locations of where an atlas will be scanned for. By default only hotbar will be scanned
#Allowed Values: MAIN_HAND, HOTBAR, HANDS, HOTBAR_AND_HANDS, INVENTORY
activationLocations = "HOTBAR_AND_HANDS"
#Allows players in creative to teleport using the atlas. Hold shift and press anywhere
creative_teleport = true
#Marker id associated with the red pin button on the atlas screen. Set to empty string to disable
pin_marked_id = "minecraft:target_point"

