#Add Entity on Looking AI Blacklist. Use the full name(This config only disabled mob enchant when mob spawn. not mean delete complete, eg: minecraft:zomibe.
LookingAIMobBlacklist = ["minecraft:phantom", "minecraft:player", "minecraft:ender_dragon"]
#Add Entity on Mob check Vibration BlackList
VibrationBlackList = ["minecraft:phantom", "minecraft:warden"]
#Add Entity on Prime Dislike List(example. They run for TNT)
PrimeDislikeBlackList = ["minecraft:creeper", "minecraft:zombie", "minecraft:skeleton", "minecraft:sheep", "minecraft:cow", "minecraft:mooshroom", "minecraft:rabbit", "minecraft:cat", "minecraft:ocelot", "minecraft:villager", "minecraft:pillager", "minecraft:evoker", "minecraft:vindicator", "minecraft:illusioner", "hunterillager:hunterillager", "minecraft:stray", "minecraft:husk", "minecraft:pig", "minecraft:chicken", "earthmobsmod:wooly_cow", "earthmobsmod:cluck_shroom", "earthmobsmod:horned_sheep", "earthmobsmod:hyper_rabbit", "earthmobsmod:moobloom", "earthmobsmod:moolip", "earthmobsmod:jumbo_rabbit"]
#Enable Mob check Vibration(when they find sounds. find sound source.)
Vibration = true
#Change Mob check Vibration Range.(It mean you can more encounter enemy)
#Range: 6 ~ 24
"Vibration Range" = 16

