#Credits for LootTables method - Fungal Infection:Spore
#item|chance to drop(1-100)|minimum amount|maximum amount.Only values above 0 will be taken in consideration.
"Flesh Human Loot" = ["the_flesh_that_hates:piece_of_flesh|60|1|1"]
"Flesh Villager Loot" = ["the_flesh_that_hates:piece_of_flesh|60|1|1"]
"Flesh Vindicator Loot" = ["the_flesh_that_hates:piece_of_flesh|80|1|2"]
"Flesh Pillager Loot" = ["the_flesh_that_hates:piece_of_flesh|60|1|2"]
"Flesh Infector Loot" = ["the_flesh_that_hates:piece_of_flesh|50|1|1"]
"Flesh Pig Loot" = ["the_flesh_that_hates:piece_of_flesh|50|1|1"]
"Flesh Cow Loot" = ["the_flesh_that_hates:piece_of_flesh|60|1|2"]
"Flesh Sheep Loot" = ["the_flesh_that_hates:piece_of_flesh|50|1|1"]
"Flesh Dog Loot" = ["the_flesh_that_hates:piece_of_flesh|80|1|3"]
"Flesh Mutant Loot" = ["the_flesh_that_hates:piece_of_flesh|100|1|2", "the_flesh_that_hates:mutant_hand|20|1|1"]
"Flesh Brute I Loot" = ["the_flesh_that_hates:piece_of_flesh|100|1|4"]
"Flesh Human Head Loot" = ["the_flesh_that_hates:piece_of_flesh|30|1|1"]
"Flesh Piece Loot" = ["the_flesh_that_hates:piece_of_flesh|20|1|1"]
"Flesh Hunter I Loot" = ["the_flesh_that_hates:piece_of_flesh|100|1|3", "the_flesh_that_hates:mutant_hand|30|1|1"]
"Flesh Hunter II Loot" = ["the_flesh_that_hates:piece_of_flesh|100|1|3", "the_flesh_that_hates:mutant_hand|30|1|1"]
"Flesh Hysterizer Loot" = ["the_flesh_that_hates:piece_of_flesh|100|2|4", "the_flesh_that_hates:mutated_flesh|50|1|2", "the_flesh_that_hates:damned_flesh_eye|5|1|1"]
"Flesh Suffer Loot" = ["the_flesh_that_hates:piece_of_flesh|20|1|1", "the_flesh_that_hates:mutant_hand|80|1|2"]
"Flesh Boomer Loot" = ["the_flesh_that_hates:piece_of_flesh|100|1|3"]
"Flesh Howler Loot" = ["the_flesh_that_hates:piece_of_flesh|100|2|3", "the_flesh_that_hates:damned_flesh_eye|10|1|1"]
"Flesh Unseen Loot" = ["the_flesh_that_hates:piece_of_flesh|100|6|10", "the_flesh_that_hates:mutated_flesh|70|2|3", "the_flesh_that_hates:flesh_heart|30|1|1"]
"Flesh Community Loot" = ["the_flesh_that_hates:piece_of_flesh|100|8|12", "the_flesh_that_hates:mutant_hand|80|3|5"]
"Flesh Justice Loot" = ["the_flesh_that_hates:piece_of_flesh|100|3|3"]
"Flesh Cocoon Loot" = ["the_flesh_that_hates:piece_of_flesh|30|1|1"]
"Flesh Servant Loot" = ["the_flesh_that_hates:piece_of_flesh|70|1|2"]
"Flesh Incubator Embryo Loot" = ["the_flesh_that_hates:piece_of_flesh|100|1|3", "the_flesh_that_hates:mutated_flesh|100|1|2", "the_flesh_that_hates:flesh_heart|10|1|1"]
"Flesh Incubator Enlightenment Loot" = ["the_flesh_that_hates:piece_of_flesh|100|14|20", "the_flesh_that_hates:mutated_flesh|100|3|5", "the_flesh_that_hates:flesh_heart|50|1|1"]

