
#Client
[client]
	"Enable entity eyes moving" = true
	"Enable vindicator animation" = true
	"Enable pillager animation" = true
	"Enable evoker animation" = true
	"Enable piglin animation" = true
	"Enable piglin brute animation" = true
	"Enable iron golem animation" = true

