
["Do Jockeys Spawn"]
	#
	#Determines whether or not Jockeys spawn (Just splits the entities if false).
	#
	vmhDoJockeysSpawn = true

["Do Scale Noise"]
	#
	#Determines whether or not to scale noise by the scale value.
	#
	vmhDoScaleNoise = true

["Entities Blacklist"]
	#
	#Determines what entities are blacklist to be used by this mod.
	#
	vmhEntitiesBlacklist = ["minecraft:ender_dragon", "minecraft:wither", "minecraft:warden"]

