
["Attack Damage Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesAttackDamage = []

["Attack Speed Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesAttackSpeed = []

["Attack Knockback Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesAttackKnockBack = []

["Defense Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesDefense = []

["Speed Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesSpeed = []

["Jump Height Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesJumpHeight = []

["Horse Jump Height Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesHorseJumpHeight = []

["Health Override"]
	#
	#Determines what entities have their values overridden by values set heren
	#The median only does things for certain distribution values.
	#
	#If an entity doesn't work automatically, this list also works as a whitelist. There is also a Blacklist, and an Inverted Entity Whitelist
	#
	#Inverted values can be set which invert the Min and Max values of a dataset for a specific.
	#
	#**Values must be set as follows: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	vmhOverridesHealth = []

